# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from belady.v1 import cache_pb2 as belady_dot_v1_dot_cache__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in belady/v1/cache_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CacheStub:
    """Cache is implemented by both the gateway and the cache nodes. The gateway is a
    routing proxy in front of the same interface, so a client can talk to either
    one and a cache node can be exercised directly in tests.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/belady.v1.Cache/Get',
                request_serializer=belady_dot_v1_dot_cache__pb2.GetRequest.SerializeToString,
                response_deserializer=belady_dot_v1_dot_cache__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Put = channel.unary_unary(
                '/belady.v1.Cache/Put',
                request_serializer=belady_dot_v1_dot_cache__pb2.PutRequest.SerializeToString,
                response_deserializer=belady_dot_v1_dot_cache__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/belady.v1.Cache/Delete',
                request_serializer=belady_dot_v1_dot_cache__pb2.DeleteRequest.SerializeToString,
                response_deserializer=belady_dot_v1_dot_cache__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/belady.v1.Cache/Stats',
                request_serializer=belady_dot_v1_dot_cache__pb2.StatsRequest.SerializeToString,
                response_deserializer=belady_dot_v1_dot_cache__pb2.StatsResponse.FromString,
                _registered_method=True)


class CacheServicer:
    """Cache is implemented by both the gateway and the cache nodes. The gateway is a
    routing proxy in front of the same interface, so a client can talk to either
    one and a cache node can be exercised directly in tests.
    """

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=belady_dot_v1_dot_cache__pb2.GetRequest.FromString,
                    response_serializer=belady_dot_v1_dot_cache__pb2.GetResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=belady_dot_v1_dot_cache__pb2.PutRequest.FromString,
                    response_serializer=belady_dot_v1_dot_cache__pb2.PutResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=belady_dot_v1_dot_cache__pb2.DeleteRequest.FromString,
                    response_serializer=belady_dot_v1_dot_cache__pb2.DeleteResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=belady_dot_v1_dot_cache__pb2.StatsRequest.FromString,
                    response_serializer=belady_dot_v1_dot_cache__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'belady.v1.Cache', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('belady.v1.Cache', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cache:
    """Cache is implemented by both the gateway and the cache nodes. The gateway is a
    routing proxy in front of the same interface, so a client can talk to either
    one and a cache node can be exercised directly in tests.
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/belady.v1.Cache/Get',
            belady_dot_v1_dot_cache__pb2.GetRequest.SerializeToString,
            belady_dot_v1_dot_cache__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/belady.v1.Cache/Put',
            belady_dot_v1_dot_cache__pb2.PutRequest.SerializeToString,
            belady_dot_v1_dot_cache__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/belady.v1.Cache/Delete',
            belady_dot_v1_dot_cache__pb2.DeleteRequest.SerializeToString,
            belady_dot_v1_dot_cache__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/belady.v1.Cache/Stats',
            belady_dot_v1_dot_cache__pb2.StatsRequest.SerializeToString,
            belady_dot_v1_dot_cache__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OriginStub:
    """Origin stands in for whatever the cache fronts: a database, an object store,
    another cache tier. The bundled implementation is a fixture with configurable
    latency and value sizes so the system runs with no external dependency.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fetch = channel.unary_unary(
                '/belady.v1.Origin/Fetch',
                request_serializer=belady_dot_v1_dot_cache__pb2.FetchRequest.SerializeToString,
                response_deserializer=belady_dot_v1_dot_cache__pb2.FetchResponse.FromString,
                _registered_method=True)


class OriginServicer:
    """Origin stands in for whatever the cache fronts: a database, an object store,
    another cache tier. The bundled implementation is a fixture with configurable
    latency and value sizes so the system runs with no external dependency.
    """

    def Fetch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OriginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fetch': grpc.unary_unary_rpc_method_handler(
                    servicer.Fetch,
                    request_deserializer=belady_dot_v1_dot_cache__pb2.FetchRequest.FromString,
                    response_serializer=belady_dot_v1_dot_cache__pb2.FetchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'belady.v1.Origin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('belady.v1.Origin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Origin:
    """Origin stands in for whatever the cache fronts: a database, an object store,
    another cache tier. The bundled implementation is a fixture with configurable
    latency and value sizes so the system runs with no external dependency.
    """

    @staticmethod
    def Fetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/belady.v1.Origin/Fetch',
            belady_dot_v1_dot_cache__pb2.FetchRequest.SerializeToString,
            belady_dot_v1_dot_cache__pb2.FetchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
