# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from belady.v1 import registry_pb2 as belady_dot_v1_dot_registry__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in belady/v1/registry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegistryStub:
    """Registry is the only thing the Python trainer and the Go cache nodes share at
    runtime: the trainer pushes a model, the cache nodes watch for it and pull it.
    Models are streamed in chunks because a LightGBM text dump grows with tree
    count and easily exceeds a comfortable unary message size.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishModel = channel.stream_unary(
                '/belady.v1.Registry/PublishModel',
                request_serializer=belady_dot_v1_dot_registry__pb2.PublishModelRequest.SerializeToString,
                response_deserializer=belady_dot_v1_dot_registry__pb2.PublishModelResponse.FromString,
                _registered_method=True)
        self.GetModel = channel.unary_stream(
                '/belady.v1.Registry/GetModel',
                request_serializer=belady_dot_v1_dot_registry__pb2.GetModelRequest.SerializeToString,
                response_deserializer=belady_dot_v1_dot_registry__pb2.GetModelResponse.FromString,
                _registered_method=True)
        self.WatchModels = channel.unary_stream(
                '/belady.v1.Registry/WatchModels',
                request_serializer=belady_dot_v1_dot_registry__pb2.WatchModelsRequest.SerializeToString,
                response_deserializer=belady_dot_v1_dot_registry__pb2.ModelEvent.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/belady.v1.Registry/ListModels',
                request_serializer=belady_dot_v1_dot_registry__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=belady_dot_v1_dot_registry__pb2.ListModelsResponse.FromString,
                _registered_method=True)


class RegistryServicer:
    """Registry is the only thing the Python trainer and the Go cache nodes share at
    runtime: the trainer pushes a model, the cache nodes watch for it and pull it.
    Models are streamed in chunks because a LightGBM text dump grows with tree
    count and easily exceeds a comfortable unary message size.
    """

    def PublishModel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishModel': grpc.stream_unary_rpc_method_handler(
                    servicer.PublishModel,
                    request_deserializer=belady_dot_v1_dot_registry__pb2.PublishModelRequest.FromString,
                    response_serializer=belady_dot_v1_dot_registry__pb2.PublishModelResponse.SerializeToString,
            ),
            'GetModel': grpc.unary_stream_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=belady_dot_v1_dot_registry__pb2.GetModelRequest.FromString,
                    response_serializer=belady_dot_v1_dot_registry__pb2.GetModelResponse.SerializeToString,
            ),
            'WatchModels': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchModels,
                    request_deserializer=belady_dot_v1_dot_registry__pb2.WatchModelsRequest.FromString,
                    response_serializer=belady_dot_v1_dot_registry__pb2.ModelEvent.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=belady_dot_v1_dot_registry__pb2.ListModelsRequest.FromString,
                    response_serializer=belady_dot_v1_dot_registry__pb2.ListModelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'belady.v1.Registry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('belady.v1.Registry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Registry:
    """Registry is the only thing the Python trainer and the Go cache nodes share at
    runtime: the trainer pushes a model, the cache nodes watch for it and pull it.
    Models are streamed in chunks because a LightGBM text dump grows with tree
    count and easily exceeds a comfortable unary message size.
    """

    @staticmethod
    def PublishModel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/belady.v1.Registry/PublishModel',
            belady_dot_v1_dot_registry__pb2.PublishModelRequest.SerializeToString,
            belady_dot_v1_dot_registry__pb2.PublishModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/belady.v1.Registry/GetModel',
            belady_dot_v1_dot_registry__pb2.GetModelRequest.SerializeToString,
            belady_dot_v1_dot_registry__pb2.GetModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/belady.v1.Registry/WatchModels',
            belady_dot_v1_dot_registry__pb2.WatchModelsRequest.SerializeToString,
            belady_dot_v1_dot_registry__pb2.ModelEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/belady.v1.Registry/ListModels',
            belady_dot_v1_dot_registry__pb2.ListModelsRequest.SerializeToString,
            belady_dot_v1_dot_registry__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
