# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: belady/v1/registry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'belady/v1/registry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x62\x65lady/v1/registry.proto\x12\tbelady.v1\"\xfb\x01\n\tModelMeta\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x12\n\nsize_bytes\x18\x03 \x01(\x04\x12\x0e\n\x06sha256\x18\x04 \x01(\t\x12\x14\n\x0c\x63reated_unix\x18\x05 \x01(\x03\x12\x15\n\rfeature_count\x18\x06 \x01(\r\x12\x18\n\x10\x62oundary_seconds\x18\x07 \x01(\r\x12\x32\n\x07metrics\x18\x08 \x03(\x0b\x32!.belady.v1.ModelMeta.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"W\n\x13PublishModelRequest\x12$\n\x04meta\x18\x01 \x01(\x0b\x32\x14.belady.v1.ModelMetaH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload\":\n\x14PublishModelResponse\x12\"\n\x04meta\x18\x01 \x01(\x0b\x32\x14.belady.v1.ModelMeta\"\"\n\x0fGetModelRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\"T\n\x10GetModelResponse\x12$\n\x04meta\x18\x01 \x01(\x0b\x32\x14.belady.v1.ModelMetaH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload\"+\n\x12WatchModelsRequest\x12\x15\n\rsince_version\x18\x01 \x01(\t\"0\n\nModelEvent\x12\"\n\x04meta\x18\x01 \x01(\x0b\x32\x14.belady.v1.ModelMeta\"\"\n\x11ListModelsRequest\x12\r\n\x05limit\x18\x01 \x01(\r\":\n\x12ListModelsResponse\x12$\n\x06models\x18\x01 \x03(\x0b\x32\x14.belady.v1.ModelMeta2\xb6\x02\n\x08Registry\x12Q\n\x0cPublishModel\x12\x1e.belady.v1.PublishModelRequest\x1a\x1f.belady.v1.PublishModelResponse(\x01\x12\x45\n\x08GetModel\x12\x1a.belady.v1.GetModelRequest\x1a\x1b.belady.v1.GetModelResponse0\x01\x12\x45\n\x0bWatchModels\x12\x1d.belady.v1.WatchModelsRequest\x1a\x15.belady.v1.ModelEvent0\x01\x12I\n\nListModels\x12\x1c.belady.v1.ListModelsRequest\x1a\x1d.belady.v1.ListModelsResponseB4Z2github.com/JustinK33/Belady/gen/belady/v1;beladyv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'belady.v1.registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/JustinK33/Belady/gen/belady/v1;beladyv1'
  _globals['_MODELMETA_METRICSENTRY']._loaded_options = None
  _globals['_MODELMETA_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_MODELMETA']._serialized_start=40
  _globals['_MODELMETA']._serialized_end=291
  _globals['_MODELMETA_METRICSENTRY']._serialized_start=245
  _globals['_MODELMETA_METRICSENTRY']._serialized_end=291
  _globals['_PUBLISHMODELREQUEST']._serialized_start=293
  _globals['_PUBLISHMODELREQUEST']._serialized_end=380
  _globals['_PUBLISHMODELRESPONSE']._serialized_start=382
  _globals['_PUBLISHMODELRESPONSE']._serialized_end=440
  _globals['_GETMODELREQUEST']._serialized_start=442
  _globals['_GETMODELREQUEST']._serialized_end=476
  _globals['_GETMODELRESPONSE']._serialized_start=478
  _globals['_GETMODELRESPONSE']._serialized_end=562
  _globals['_WATCHMODELSREQUEST']._serialized_start=564
  _globals['_WATCHMODELSREQUEST']._serialized_end=607
  _globals['_MODELEVENT']._serialized_start=609
  _globals['_MODELEVENT']._serialized_end=657
  _globals['_LISTMODELSREQUEST']._serialized_start=659
  _globals['_LISTMODELSREQUEST']._serialized_end=693
  _globals['_LISTMODELSRESPONSE']._serialized_start=695
  _globals['_LISTMODELSRESPONSE']._serialized_end=753
  _globals['_REGISTRY']._serialized_start=756
  _globals['_REGISTRY']._serialized_end=1066
# @@protoc_insertion_point(module_scope)
