# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: belady/v1/trace.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'belady/v1/trace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x65lady/v1/trace.proto\x12\tbelady.v1\"W\n\x0c\x41\x63\x63\x65ssRecord\x12\x10\n\x08key_hash\x18\x01 \x01(\x04\x12\x14\n\x0ctimestamp_us\x18\x02 \x01(\x03\x12\x12\n\nsize_bytes\x18\x03 \x01(\r\x12\x0b\n\x03hit\x18\x04 \x01(\x08\"Z\n\x0b\x41\x63\x63\x65ssBatch\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\x04\x12(\n\x07records\x18\x03 \x03(\x0b\x32\x17.belady.v1.AccessRecordB5Z3github.com/JustinK33/newproj/gen/belady/v1;beladyv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'belady.v1.trace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/JustinK33/newproj/gen/belady/v1;beladyv1'
  _globals['_ACCESSRECORD']._serialized_start=36
  _globals['_ACCESSRECORD']._serialized_end=123
  _globals['_ACCESSBATCH']._serialized_start=125
  _globals['_ACCESSBATCH']._serialized_end=215
# @@protoc_insertion_point(module_scope)
